---
grails:
    profile: web
    codegen:
        defaultPackage: siakad
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    devtools:
        restart:
            additional-exclude:
                - '*.gsp'
                - '**/*.gsp'
                - '*.gson'
                - '**/*.gson'
                - 'logback.groovy'
                - '*.properties'
environments:
    development:
        management:
            endpoints:
                enabled-by-default: true
                web:
                    base-path: '/actuator'
                    exposure:
                        include: '*'
    production:
        management:
            endpoints:
                enabled-by-default: false

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlet: html
                taglib: none
                staticparts: none

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
    pooled: true
    jmxExport: true
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: "root"
    password: "password"
    dialect: "org.hibernate.dialect.MySQL8Dialect"

environments:
    development:
        dataSource:
            dbCreate: update
            url: "jdbc:mysql://localhost:1234/db_fairtech_siakad?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false"
    test:
        dataSource:
            dbCreate: update
            url: "jdbc:mysql://localhost:1234/db_fairtech_siakad_test?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false"
    production:
        dataSource:
            dbCreate: none
            url: "jdbc:mysql://localhost:1234/db_fairtech_siakad?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false"
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
grails:
    plugin:
        springsecurity:
            active: true
            securityConfigType: 'InterceptUrlMap'
            interceptUrlMap:
                - pattern: '/user/index'
                  access: ['IS_AUTHENTICATED_FULLY']
                - pattern: '/**'
                  access: ['IS_AUTHENTICATED_ANONYMOUSLY']
            userLookup:
                typeMappings:
                    student:
                        userDomainClassName: 'siakad.Student'
                        usernamePropertyName: 'nim'
                        passwordPropertyName: 'password'
                    lecturer:
                        userDomainClassName: 'siakad.Lecturer'
                        usernamePropertyName: 'nim'
                        passwordPropertyName: 'password'
            password:
                algorithm: 'bcrypt'
                strength: 10
